package com.chinamobile.pcrf;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * PCRFSoap service = new PCRFSoap();
 * ScfPccSoapServiceEndpoint portType = service.getChinaMobilePCRFSoapServiceEndpointPort();
 * portType.addSubscriber(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "PCRFSoap", targetNamespace = "http://www.chinamobile.com/PCRF/", wsdlLocation = "file:/C:/Users/Administrator/Desktop/pcrf_new.wsdl")
public class PCRFSoap extends Service {

	private final static URL PCRFSOAP_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.chinamobile.pcrf.PCRFSoap.class.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.chinamobile.pcrf.PCRFSoap.class.getResource(".");
			url = new URL(baseUrl,
					"file:/C:/Users/Administrator/Desktop/pcrf_new.wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'file:/C:/Users/Administrator/Desktop/pcrf_new.wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		PCRFSOAP_WSDL_LOCATION = url;
	}

	public PCRFSoap(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public PCRFSoap() {
		super(PCRFSOAP_WSDL_LOCATION, new QName(
				"http://www.chinamobile.com/PCRF/", "PCRFSoap"));
	}

	/**
	 * 
	 * @return returns ScfPccSoapServiceEndpoint
	 */
	@WebEndpoint(name = "ChinaMobilePCRFSoapServiceEndpointPort")
	public ScfPccSoapServiceEndpoint getChinaMobilePCRFSoapServiceEndpointPort() {
		return super.getPort(new QName("http://www.chinamobile.com/PCRF/",
				"ChinaMobilePCRFSoapServiceEndpointPort"),
				ScfPccSoapServiceEndpoint.class);
	}

}
